{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels: {{- include "de-stack.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "de-stack.selector" (dict "app" "redis") | nindent 6 }}
  template:
    metadata:
      labels: {{- include "de-stack.selector" (dict "app" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 6379
          readinessProbe:
            exec: { command: ["redis-cli", "ping"] }
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels: {{- include "de-stack.labels" . | nindent 4 }}
spec:
  selector: {{- include "de-stack.selector" (dict "app" "redis") | nindent 4 }}
  ports:
    - { name: redis, port: 6379, targetPort: 6379 }
{{- end }}
