
services:
  app-orders:
    container_name: app-orders
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.app
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      TOPIC_NAME: orders
      DB_HOST: postgres
    command: python /code/northwind/orders-generator.py
    restart: always
    volumes:
      - ./code:/code
    networks:
      - sparknet
  
  app-price-updates:
    container_name: app-price-updates
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.app
    depends_on:
      - kafka
    environment:
      DB_HOST: postgres
    command: python /code/northwind/product-price-generator.py
    restart: always
    volumes:
      - ./code:/code
    networks:
      - sparknet

  app-user-session-flow:
    container_name: app-user-session-flow
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.app
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      TOPIC_NAME: user_clickstream
      DB_HOST: postgres
    command: python /code/northwind/user-click-sessions.py
    restart: always
    volumes:
      - ./code:/code
    networks:
      - sparknet