version: '3.8'

services:
  superset:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.superset
    container_name: superset
    restart: always
    ports:
      - "8004:8088"
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key
      - DATABASE_URL=postgresql+psycopg2://superset:superset@postgres:5432/superset
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CSRF_ENABLED=False
      - WTF_CSRF_ENABLED=False
      - TALISMAN_ENABLED=False
    depends_on:
      - postgres
      - redis
    command: >
      /bin/bash -c "
        pip install psycopg2-binary &&
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init && python /extras/connections.py &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "
    networks:
      - sparknet